/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RentRouteImport } from './routes/rent'
import { Route as NewProjectsRouteImport } from './routes/new-projects'
import { Route as ListYourPropertyRouteImport } from './routes/list-your-property'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommercialRouteImport } from './routes/commercial'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const RentRoute = RentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const NewProjectsRoute = NewProjectsRouteImport.update({
  id: '/new-projects',
  path: '/new-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ListYourPropertyRoute = ListYourPropertyRouteImport.update({
  id: '/list-your-property',
  path: '/list-your-property',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialRoute = CommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/blog': typeof BlogRoute
  '/buy': typeof BuyRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/list-your-property': typeof ListYourPropertyRoute
  '/new-projects': typeof NewProjectsRoute
  '/rent': typeof RentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/blog': typeof BlogRoute
  '/buy': typeof BuyRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/list-your-property': typeof ListYourPropertyRoute
  '/new-projects': typeof NewProjectsRoute
  '/rent': typeof RentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/blog': typeof BlogRoute
  '/buy': typeof BuyRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/list-your-property': typeof ListYourPropertyRoute
  '/new-projects': typeof NewProjectsRoute
  '/rent': typeof RentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agents'
    | '/blog'
    | '/buy'
    | '/commercial'
    | '/contact'
    | '/list-your-property'
    | '/new-projects'
    | '/rent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agents'
    | '/blog'
    | '/buy'
    | '/commercial'
    | '/contact'
    | '/list-your-property'
    | '/new-projects'
    | '/rent'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agents'
    | '/blog'
    | '/buy'
    | '/commercial'
    | '/contact'
    | '/list-your-property'
    | '/new-projects'
    | '/rent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgentsRoute: typeof AgentsRoute
  BlogRoute: typeof BlogRoute
  BuyRoute: typeof BuyRoute
  CommercialRoute: typeof CommercialRoute
  ContactRoute: typeof ContactRoute
  ListYourPropertyRoute: typeof ListYourPropertyRoute
  NewProjectsRoute: typeof NewProjectsRoute
  RentRoute: typeof RentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rent': {
      id: '/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof RentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-projects': {
      id: '/new-projects'
      path: '/new-projects'
      fullPath: '/new-projects'
      preLoaderRoute: typeof NewProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-your-property': {
      id: '/list-your-property'
      path: '/list-your-property'
      fullPath: '/list-your-property'
      preLoaderRoute: typeof ListYourPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial': {
      id: '/commercial'
      path: '/commercial'
      fullPath: '/commercial'
      preLoaderRoute: typeof CommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgentsRoute: AgentsRoute,
  BlogRoute: BlogRoute,
  BuyRoute: BuyRoute,
  CommercialRoute: CommercialRoute,
  ContactRoute: ContactRoute,
  ListYourPropertyRoute: ListYourPropertyRoute,
  NewProjectsRoute: NewProjectsRoute,
  RentRoute: RentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
