import {useEffect,useRef,useState} from 'react';
import {ExternalLink} from 'lucide-react';
import PageIntro from '../components/PageIntro';
import type {SiteConfig} from '../lib/siteConfig';
import {emitAnalytics} from '../lib/analytics';
export default function BookingPage({config}:{config:SiteConfig}){
 const [showCalendar,setShowCalendar]=useState(false);const frame=useRef<HTMLIFrameElement>(null);const completed=useRef(false);
 useEffect(()=>{const onMessage=(event:MessageEvent)=>{if(event.origin!==new URL(config.bookingUrl).origin||event.source!==frame.current?.contentWindow||!event.data||typeof event.data!=='object')return;if(event.data.event==='calendly.event_scheduled'&&!completed.current){completed.current=true;emitAnalytics('booking_complete','/book-a-strategy-call/');}};window.addEventListener('message',onMessage);return()=>window.removeEventListener('message',onMessage);},[config.bookingUrl]);
 return <div className="page-shell"><div className="site-container"><PageIntro eyebrow="Start a conversation" title="Book a strategy call." description="Choose a convenient time to discuss your goals, constraints and the most useful next step."/><div className="card mt-12 overflow-hidden">{showCalendar?<iframe ref={frame} src={config.bookingUrl} title="Book an ITGS strategy call" className="h-[720px] w-full"/>:<div className="p-8"><p className="max-w-2xl leading-7">Scheduling is provided by Calendly. Loading the calendar connects to Calendly and its service providers. You can also open the scheduler directly.</p><button onClick={()=>{setShowCalendar(true);emitAnalytics('booking_start','/book-a-strategy-call/');}} className="btn-primary mt-6">Load scheduling calendar</button></div>}</div><p className="mt-5 text-sm">Calendar not loading? <a href={config.bookingUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center gap-1 font-semibold text-electric" onClick={()=>emitAnalytics('booking_start','/book-a-strategy-call/')}>Open Calendly <ExternalLink size={14}/></a></p>{config.privacyUrl&&<p className="mt-4"><a href={config.privacyUrl} className="underline">Read our privacy notice</a></p>}</div></div>;
}
