import { ArrowDown, ArrowRight, ArrowUpRight, Blocks, Code2, Gauge, Search, ShoppingBag, Target, Workflow, type LucideIcon } from 'lucide-react';
import { ApprovedCaseStudies, ApprovedProofBar } from '../components/home/ApprovedContentSections';
import { pathForPage, servicePath, trackSiteEvent } from '../lib/siteNavigation';
import IconBadge from '../components/IconBadge';

type Props = { setActivePage: (page: string) => void };

type Solution = {
  id: string;
  title: string;
  problem: string;
  outcome: string;
  startingPoint: string;
  capabilities: { id: string; label: string }[];
  icon: LucideIcon;
};

const solutions: Solution[] = [
  { id: 'launch-digital-product', title: 'Launch a digital product', problem: 'You have an opportunity or defined idea, but need to turn it into a usable product and release plan.', outcome: 'A focused website, web application, mobile product or digital experience shaped around real users and operating needs.', startingPoint: 'Product definition and experience scope', capabilities: [{ id: 'ui-ux-design', label: 'UI/UX Design' }, { id: 'web-development', label: 'Web Development' }, { id: 'mobile-development', label: 'Mobile App Development' }], icon: Code2 },
  { id: 'modernize-product', title: 'Modernize an existing product', problem: 'An existing website or application is difficult to use, maintain, extend or discover.', outcome: 'A clearer experience and a practical modernization route across design, technology and migration risk.', startingPoint: 'Product, UX and technical assessment', capabilities: [{ id: 'ui-ux-design', label: 'UI/UX Design' }, { id: 'web-development', label: 'Web Development' }, { id: 'seo', label: 'SEO migration support' }], icon: Gauge },
  { id: 'improve-organic-visibility', title: 'Improve organic visibility', problem: 'Important pages are difficult for search engines and prospective customers to find or understand.', outcome: 'Stronger technical foundations, intent-led architecture and clearer paths from discovery to useful content.', startingPoint: 'Search and website diagnosis', capabilities: [{ id: 'seo', label: 'Search Engine Optimization' }, { id: 'web-development', label: 'Web Development' }, { id: 'ui-ux-design', label: 'UI/UX Design' }], icon: Search },
  { id: 'generate-qualified-demand', title: 'Generate qualified demand', problem: 'Acquisition activity is not producing enough relevant opportunities or a clear path into sales follow-up.', outcome: 'A connected audience, acquisition, conversion and qualification system built around useful demand.', startingPoint: 'Audience, offer and funnel assessment', capabilities: [{ id: 'digital-marketing', label: 'Digital Marketing' }, { id: 'lead-generation', label: 'Lead Generation' }, { id: 'seo', label: 'SEO' }], icon: Target },
  { id: 'strengthen-online-commerce', title: 'Strengthen online commerce', problem: 'Storefront experience, marketplace operations, catalog work and growth activity are disconnected.', outcome: 'A clearer commerce model connecting customer experience, technology, operations and measurement.', startingPoint: 'Commerce model and operations assessment', capabilities: [{ id: 'e-commerce', label: 'E-commerce Solutions' }, { id: 'web-development', label: 'Web Development' }, { id: 'digital-marketing', label: 'Digital Marketing' }, { id: 'seo', label: 'SEO' }], icon: ShoppingBag },
  { id: 'improve-digital-operations', title: 'Improve digital operations', problem: 'Recurring administrative work, manual handoffs and unclear ownership are slowing the team down.', outcome: 'A documented operating model that identifies what should be delegated, improved or automated.', startingPoint: 'Workflow and responsibility mapping', capabilities: [{ id: 'virtual-assistance', label: 'Virtual Assistance' }, { id: 'web-development', label: 'Workflow technology' }], icon: Workflow },
];

export default function SolutionsPage({ setActivePage }: Props) {
  const discussGoal = (location: string) => {
    trackSiteEvent('discuss_solution_goal', { location });
    setActivePage('Booking');
  };
  return <div className="bg-white">
    <section className="hero-atmosphere pb-16 pt-28 text-white md:pb-20 md:pt-32"><div className="site-container"><nav className="mb-8 text-sm text-white/65" aria-label="Breadcrumb"><ol className="flex items-center gap-2"><li><a href={pathForPage('Home')} onClick={(event) => { event.preventDefault(); setActivePage('Home'); }} className="inline-flex min-h-11 items-center hover:text-white">Home</a></li><li aria-hidden="true" className="text-white/35">/</li><li aria-current="page" className="text-white">Solutions</li></ol></nav><div className="grid gap-10 lg:grid-cols-[1fr_.72fr] lg:items-end"><div><span className="mb-5 block text-[11px] font-semibold uppercase tracking-[.17em] text-sky">ITGS solutions</span><h1 className="max-w-4xl text-balance text-[clamp(2.8rem,5.5vw,5rem)] font-semibold leading-[1.01] tracking-[-.055em] text-white">Start with the <span className="text-sky">business outcome.</span></h1></div><div><p className="max-w-xl text-lg leading-8 text-[#d3e0ed]">Explore solutions organized around what you are trying to launch, improve, grow or operate—not around internal departments.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><a href="#solution-paths" className="btn-primary">Explore solutions <ArrowDown size={17} /></a><a href={pathForPage('Booking')} onClick={(event) => { event.preventDefault(); discussGoal('hero'); }} className="btn-outline-dark">Discuss your goal <ArrowUpRight size={17} /></a></div></div></div></div></section>

    <ApprovedProofBar />

    <section id="solution-paths" className="section-space scroll-mt-28 bg-white" aria-labelledby="solution-paths-title"><div className="site-container"><span className="eyebrow">Problem discovery</span><h2 id="solution-paths-title" className="max-w-4xl text-[clamp(2.25rem,4vw,3.55rem)] leading-[1.08]">What are you trying to achieve?</h2><p className="mt-5 max-w-3xl text-lg leading-8">Choose the closest outcome. Each path can combine more than one ITGS capability, but the recommended starting point stays focused.</p><div className="mt-11 grid gap-5 lg:grid-cols-2">{solutions.map((solution, index) => <article id={solution.id} key={solution.id} className="scroll-mt-28 rounded-xl border border-border bg-[#fbfdff] p-7 md:p-8"><div className="flex items-start justify-between gap-4"><IconBadge><solution.icon size={24} /></IconBadge><span className="text-xs font-semibold text-steel">0{index + 1}</span></div><h3 className="mt-6 text-2xl">{solution.title}</h3><dl className="mt-6 grid gap-5 text-sm leading-6"><div><dt className="font-semibold text-ink">Business problem</dt><dd className="mt-1">{solution.problem}</dd></div><div><dt className="font-semibold text-ink">Desired outcome</dt><dd className="mt-1">{solution.outcome}</dd></div><div><dt className="font-semibold text-ink">Recommended starting point</dt><dd className="mt-1 text-[#174c87]">{solution.startingPoint}</dd></div></dl><div className="mt-6 flex flex-wrap gap-2" aria-label={`Relevant capabilities for ${solution.title}`}>{solution.capabilities.map((capability) => <a key={capability.id} href={servicePath(capability.id)} onClick={(event) => { event.preventDefault(); trackSiteEvent('solution_service_click', { solution: solution.id, service: capability.id }); setActivePage(`Service:${capability.id}`); }} className="inline-flex min-h-10 items-center rounded-full border border-[#cfe0f5] bg-white px-3 text-xs font-semibold text-[#174c87] hover:border-electric">{capability.label}</a>)}</div></article>)}</div></div></section>

    <section className="section-space bg-[#eaf4fc]" aria-labelledby="solution-model-title"><div className="site-container grid gap-12 lg:grid-cols-[.78fr_1.22fr] lg:gap-20"><div><span className="eyebrow">How to choose</span><h2 id="solution-model-title" className="text-[clamp(2.2rem,3.8vw,3.3rem)] leading-[1.08]">The problem determines the path.</h2><p className="mt-5 text-base leading-7">A solution may cross design, development, growth and operations. The engagement still begins with one clear problem, an appropriate diagnostic step and defined responsibilities.</p></div><ol className="grid gap-4 sm:grid-cols-2"><li className="card p-6"><span className="text-sm font-semibold text-electric">01</span><h3 className="mt-4 text-xl">Describe the change</h3><p className="mt-3 text-sm leading-6">What should become easier, faster, clearer or more effective?</p></li><li className="card p-6"><span className="text-sm font-semibold text-electric">02</span><h3 className="mt-4 text-xl">Understand the current state</h3><p className="mt-3 text-sm leading-6">Review users, systems, evidence, constraints and ownership.</p></li><li className="card p-6"><span className="text-sm font-semibold text-electric">03</span><h3 className="mt-4 text-xl">Choose the starting point</h3><p className="mt-3 text-sm leading-6">Select the smallest useful diagnostic or delivery scope.</p></li><li className="card p-6"><span className="text-sm font-semibold text-electric">04</span><h3 className="mt-4 text-xl">Connect capabilities carefully</h3><p className="mt-3 text-sm leading-6">Add disciplines only when they materially affect the outcome.</p></li></ol></div></section>

    <ApprovedCaseStudies />

    <section className="hero-atmosphere py-16 text-white md:py-20" aria-labelledby="solutions-closing-title"><div className="site-container"><Blocks className="text-sky" size={28} /><p className="mb-4 mt-6 text-[11px] font-semibold uppercase tracking-[.17em] text-sky">Need help finding the path?</p><h2 id="solutions-closing-title" className="max-w-4xl text-[clamp(2.4rem,4.5vw,4rem)] leading-[1.08] text-white">Not sure which solution fits?</h2><p className="mt-5 max-w-2xl text-base leading-7 text-white/75">Tell us what you are trying to change. We will help identify the most useful starting point and the capabilities that genuinely support it.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href={pathForPage('Booking')} onClick={(event) => { event.preventDefault(); discussGoal('closing'); }} className="btn-primary">Discuss your goal <ArrowRight size={18} /></a><a href={pathForPage('Services')} onClick={(event) => { event.preventDefault(); setActivePage('Services'); }} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-md border border-white/30 px-5 text-sm font-semibold text-white hover:bg-white/10">Explore services <ArrowRight size={17} /></a></div></div></section>
  </div>;
}

